name: Static Code Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  build:
    name: Run SonarScanner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
      PHP_VERSION: 8.3
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: none
          coverage: none

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8

      - name: Run build-wrapper
        run: |
          phpize
          ./configure --enable-coverage
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} make coverage
        env:
          NO_INTERACTION: "1"
          REPORT_EXIT_STATUS: "1"
          TEST_PHP_EXECUTABLE: "/usr/bin/php"

      - name: Run sonar-scanner
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            "-Dsonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json" -Dsonar.cfamily.gcov.reportsPath=.
